[alembic]

script_location = alembic


sqlalchemy.url = postgresql://postgres:1039Gau41`*din@localhost:5432/company


log_file = alembic.log
log_level = DEBUG

[loggers]
keys = root, sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_sqlalchemy.engine]
level = INFO
handlers = console
qualname = sqlalchemy.engine


[handler_console]
class = StreamHandler
level = DEBUG
formatter = generic
args = []

[formatter_generic]
format = %(asctime)s [%(levelname)s]: %(message)s
datefmt = %Y-%m-%d %H:%M:%S